<?php

if (isset($message)) {
    echo '<div class="alert alert-danger" role="alert"><strong>', $message, '</strong></div>';
}

?>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <form action="" method="post">
            <label style="display:block">Username: </label><input id="username" name="username" type="text" value="phpdev">
            <label style="display:block;margin-top:7px;">Password: </label><input id="password" name="password" type="password" value="home">
            <div style="margin-top:7px;"><button class="btn btn-lg btn-primary" type="submit">Sign in</button></div>
        </form>
    </div>
</div>
