<?php

if ($msg = $this->{'session\messages'}('login')) {
    echo '<div class="alert alert-' . $msg['type'] . '" role="alert"><strong>', $msg['message'], '</strong></div>';
}

?>
<div class="d-inline-flex my-5">
    <form action="" method="post">
        <div class="form-group">
            <label for="username">Username</label>
            <input id="username" class="form-control" name="username" type="text" value="phpdev">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input id="password" class="form-control" name="password" type="password" value="home">
        </div>
        <button type="submit" class="btn btn-lg btn-primary">Sign in</button>
    </form>
</div>
<?php

isset($params) &&
    var_dump(['params' => $params]);
