<div class="jumbotron">
    <h1><a href="<?= $this->url('dashboard') ?>">Dashboard</a></h1>
    <p class="lead">Demo Application</p>
    <pre><?= __FILE__; ?></pre>
    <p>
        <a class="btn btn-lg btn-primary" href="<?= $this->url('dashboard/add', ['author' => 'owner', 'category' => 'oop']) ?>" role="button">Add</a>
        <a style="margin-left:10px;" class="btn btn-lg btn-primary" href="<?= $this->url('dashboard/remove') ?>" role="button">Remove</a>
    </p>
</div>

