<?php

/** @var Home\Model $this */

?>
<div class="jumbotron">
    <h1><a href="<?= $this->url('blog') ?>"><?= $this->blogTitle() ?></a></h1>
    <p class="lead"><?= $this['message'] ?: 'Demo web application page.'; ?></p>
    <pre><?= $this['server']->documentRoot(); ?></pre>
    <p>
        <a class="btn btn-lg btn-success" href="<?= $this->url('blog/create', ['author' => 'owner', 'category' => 'oop']) ?>" role="button">Create Blog Action</a>
        <a style="margin-left:10px;" class="btn btn-lg btn-success" href="<?= $this->url('blog/remove') ?>" role="button">Remove Blog Action</a>
    </p>
</div>
<?php

var_dump($this['server']->uri());
