<?php

/** @var Home\Model $this */

if ($message = $this->plugin('session')->get('login')) {
    echo '<div class="alert alert-info" role="alert"><strong>', $message, '</strong></div>';
    $this->plugin('session')->remove('login');
}

?>
<div class="jumbotron">
    <h1><a href="<?= $this->url('blog') ?>"><?= $this->blogTitle() ?></a></h1>
    <p class="lead"><?= $this['message'] ?: 'Demo web application page.'; ?></p>
    <pre><?= __FILE__; ?></pre>
    <div id="ajax-result"></div>
    <p>
        <a class="btn btn-lg btn-primary" href="<?= $this->url('blog/create', ['author' => 'owner', 'category' => 'oop']) ?>" role="button">Create Blog Action</a>
        <a style="margin-left:10px;" class="btn btn-lg btn-primary" href="<?= $this->url('blog/remove') ?>" role="button">Remove Blog Action</a>
        <a style="margin-left:10px;" class="btn btn-success btn-lg" href="#" role="button" onclick="return ajaxAction();">Version Info</a>
        <a style="margin-left:10px;" class="btn btn-success btn-lg" href="#" role="button" onclick="return ajaxHtmlAction();">About</a>
    </p>
</div>
<script type="text/javascript">
function ajaxAction() {
    $('#ajax-result').empty();
    $.getJSON('<?php echo $this->url('app', ['controller' => 'status']); ?>', [], function(data) {
        var $div = $('#ajax-result');

        $div.addClass('alert alert-success');

        $div.append('<h4>Version Information</h4>');

        var items = [];
        $.each(data, function( key, val ) {
            items.push('<li>' + key + ': ' + val + '</li>');
        });

        $('<ul/>', {
            html: items.join('')
        }).appendTo($div);
    });

    return false;
}
function ajaxHtmlAction() {
    $('#ajax-result').empty();
    $.get('<?php echo $this->url('app', ['controller' => 'about']); ?>', [], function(data) {
        var $div = $('#ajax-result');

        $div.addClass('alert alert-success');

        $div.append('<p>'+data+'</p>');
    });

    return false;
}
</script>
<?php

echo $this->render('home/extra', ['uri' => $this['request']->uri()]);
