<?php

/** @var Home\ViewModel $this */

//requires shared service layout configuration
//$this->shared('layout')['page']['title'] = 'Mvc5 Application: Home';

?>
<div class="jumbotron">
    <h1><a href="<?= $this->url('home') ?>"><?= $this->title() ?></a></h1>
    <p class="lead"><?= $this['message'] ?></p>
    <pre><?= __FILE__; ?></pre>
    <div id="ajax-result"></div>
    <p>
        <a class="btn btn-primary btn-lg" href="#" role="button" onclick="return info();">Info</a>
        <a class="btn btn-primary btn-lg" href="#" role="button" onclick="return about();">About</a>
        <a class="btn btn-primary btn-lg" href="#" role="button" onclick="return demo();">Demo</a>
    </p>
</div>
<script type="text/javascript">
function info() {
    $('#ajax-result').empty();
    $.getJSON('<?php echo $this->url(['app', 'controller' => 'status']); ?>', [], function(data) {
        var $div = $('#ajax-result');

        $div.addClass('alert alert-success');
        $div.css('overflow-x', 'auto');

        $div.append('<h4>Version Information</h4>');

        var items = [];
        $.each(data, function( key, val ) {
            items.push('<li>' + key + ': ' + val + '</li>');
        });

        $('<ul/>', {
            html: items.join('')
        }).appendTo($div);
    });

    return false;
}
function about() {
    $('#ajax-result').empty();
    $.get('<?php echo $this->url(['app', 'controller' => 'about']); ?>', [], function(data) {
        var $div = $('#ajax-result');

        $div.addClass('alert alert-success');

        $div.append('<h4>'+data+'</h4>');
    });

    return false;
}
function demo() {
    $('#ajax-result').empty();
    $.get('<?php echo $this->url(['app', 'controller' => 'demo']); ?>', [], function(data) {
        var $div = $('#ajax-result');

        $div.removeClass('alert alert-success');

        $div.append('<pre>'+data+'</pre>');
    });

    return false;
}
</script>
<?php

echo $this->render('/home/extra', ['request' => $request]);
