<?php

/** @var Mvc5\Model\Layout $this */

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>Mvc5 Playground</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <!-- Bootstrap core CSS -->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="//oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<!-- Fixed navbar -->
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Mvc5 Playground</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/overview">Overview</a></li>
                <?php

                if ($this->plugin('user')->authenticated()) {
                    echo '<li><a href="/dashboard">Dashboard</a></li>',
                         '<li><a href="/logout">Logout</a></li>';
                } else {
                    echo '<li><a href="/login">Login</a></li>';
                }

                ?>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>
<div class="container" style="margin-top:55px">
    <?php

    if ($msg = $this->{'session\messages'}()) {
        echo '<div class="alert alert-' . $msg['type'] . '" role="alert"><strong>', $msg['message'], '</strong></div>';
    }

    ?>
    <div class="row">
        <div class="col-md-12">
            <?php

            echo $this->model();

            ?>

            <div class="footer" style="border-top:1px solid #e5e5e5;margin-top:19px;padding-top:19px;">
                <p>&copy; <?= date('Y'); ?></p>
            </div>

        </div><!--/col-12-->
    </div>
</div>


<!-- script references -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>
