<?php

/** @var Mvc5\Model\Layout $this */

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>Mvc5 Playground</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <!-- Bootstrap core CSS -->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<?php

    echo $this->render('navbar', ['blog_link' => '/blog']);
    //echo $this->render(__DIR__ . '/navbar.phtml', ['blog_link' => '/blog']);
    //echo $this->render(new Mvc5\Model('navbar', ['blog_link' => '/blog']));
    //echo $this->render(new Mvc5\Model('navbar', ['blog_link' => '/b']), ['blog_link' => '/blog']);

?>
<div class="container" style="margin-top:55px">
    <div class="row">
        <div class="col-md-12">
            <?php

            echo $this->model();

            ?>

            <div class="footer">
                <p>&copy; <?= date('Y'); ?></p>
            </div>

        </div><!--/col-12-->
    </div>
</div>


<!-- script references -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</body>
</html>